services:
  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_db

  backend:
    image: mangekyokay/workshop-backend:1.1 # your already built image
    container_name: workshop_backend
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/main_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CORS_ALLOWED_ORIGINS: http://localhost:5173
    depends_on:
      - db
